blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # None
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path("postblog/", views.postBlog, name="postblog"),
]

blogmond/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):

    title = models.CharField(max_length=250)
    pub_date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='images/')
    body = models.TextField()

    def __str__(self):
        return self.title


class Quotes(models.Model):
    quote = models.TextField()
    author = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = "Quotes of the day"

    def __str__(self):
        return self.quote[:20]+"... -> "+self.author

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Post, Breaking, Tv, Series


def index(request):
    if request.method == 'GET' and request.GET.get('query') != None:
        query = request.GET.get('query')
        posts = Post.objects.filter(
            title__icontains=query)
        #quotes = Quotes.objects.order_by('-pk')[:1]

        #for quote in quotes:
        #    quote = get_object_or_404(Quotes, pk=quote.id)
        return render(request, 'blog/index.html', {'posts': posts})

    else:
    	breaking = Breaking.objects.order_by('-pub_date')[0]
    	tv = Tv.objects.order_by('-pub_date')[:5]
    	series = Series.objects.order_by('-pub_date')[:5]
    	posts = Post.objects.order_by('-pub_date')[:5]
    	all_posts = Post.objects.order_by("-pub_date")[:12]
    	context = {'posts': posts, "all_posts":all_posts, "breaking":breaking, "tv":tv, "series":series}
    	return render(request, 'blog/index.html', context)

blog/templates/blog/all_post.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogsmond All Post{% endblock title %}

{% block content %}

	<div class="container">
		
		 <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">All Posts</h5>
                <div class="card-body">
                	<div class="row">
                		{% for post in posts %}
							<div class="col-sm-3">
								<div class="card my-3">
									<div class="card-body">
										<a href="{% url 'blog:post_detail' post.id %}">
											<img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap" width="50px" height="100px">
										</a>
									</div>
									<div class="card-footer text-muted">
										<a href="{% url 'blog:post_detail' post.id %}">
											{{ post.title }}
										</a>
									</div>
								</div>
							 </div>
						{% endfor %}	
					</div>
                </div>
            </div>


	</div>

{% endblock content %}

blog/templates/blog/all_series.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogsmond All Series{% endblock title %}

{% block content %}

	<div class="container">
		
		 <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">All Series</h5>
                <div class="card-body">
                	<div class="row">
                		{% for post in series %}
							<div class="col-sm-3">
								<div class="card my-3">
									<div class="card-body">
										<a href="{% url 'blog:series_detail' post.id %}">
											<img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap" width="50px" height="100px">
										</a>
									</div>
									<div class="card-footer text-muted">
										<a href="{% url 'blog:series_detail' post.id %}">
											{{ post.title }}
										</a>
									</div>
								</div>
							 </div>
						{% endfor %}	
					</div>
                </div>
            </div>


	</div>

{% endblock content %}

blog/templates/blog/all_tv.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogsmond All Series{% endblock title %}

{% block content %}

	<div class="container">
		
		 <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">All TVs</h5>
                <div class="card-body">
                	<ul>
                		{% for each_tv in tvs %}
		            		<li>
		            			<a href="{% url 'blog:tv_detail' each_tv.id %}" />
		            				{{ each_tv.title }}
		            			</a>
		            		</li>
                		{% endfor %}
                	</ul>
                </div>
            </div>


	</div>

{% endblock content %}

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{% block title %}{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
        crossorigin="anonymous">
    <style>
        .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      
	#imgcover {
	  border: 2px;
	  padding: 25px;
	  color: #fff;
	  height: 300px;
	  background: url({% static 'blog/images/blog.png' %});
	  background-repeat: no-repeat;
	  background-size: 100% 100%;
	}

    </style>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'blog:index' %}">BLOGSMOND</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link {% block blogactive %}{% endblock blogactive %}" href="{% url 'blog:index' %}"><i
                                class="fas fa-blog"></i>Blogsmond</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <main role="main">


        {% block content %}

        {% endblock content %}

    </main>

    <footer class="text-muted">
        <div class="container text-center">
            <p>&copy; BLOGSMOND I {% now 'Y' %}</p>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/breaking_detail.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogsmond Breaking-Details{% endblock title %}

{% block content %}

	<div class="container">

		<div class="row">
		    <!-- Blog Entries Column -->
		    <div class="col-md-12">

		        <h3 class="my-4" style="color:teal;">{{ breaking.title }}</h3>
		        <hr>
		        <p> Posted on {{ breaking.pub_date }}</p>
		        <hr>

		        <!-- Blog Post -->
		        <div class="card mb-4">
		            <img class="card-img-top" src="{{ breaking.image.url }}" alt="Card image cap" width="750px" height="450px">
		            <div class="card-body">
		                <p class="card-text">{{ breaking.body }}</p>
		            </div>
		        </div>

		    </div>
		</div>

	</div>

{% endblock content %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blog-Details{% endblock title %}

{% block content %}
<!-- all posts -->
<div class="container">

    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-12">

            <h1 class="my-4" style="color:teal;">{{ post.title }}</h1>
            <hr>
            <p> Posted on {{ post.pub_date }}</p>
            <hr>

            <!-- Blog Post -->
            <div class="card mb-4">
                <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap" width="750px" height="450px">
                <div class="card-body">
                    <p class="card-text">{{ post.body }}</p>
                </div>
            </div>

        </div>
    </div>

</div>
<!-- /.row -->
	<br />
	<br />
	<br />
	<br />

		<div class="row pt-3 text-center container">
			<h1 class="my-4">Recents Post</h1>
		</div>
		
		<div class="row">
				
	            {% for post in posts %}
		        <div class="card col-md-3">
		            <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap" width="750px" height="300px">
		            <div class="card-body">
		                <h2 class="card-title" style="color:teal;">{{ post.title }}</h2>
		                <p class="card-text">{{ post.body|truncatewords:15 }}</p>
		                <a href="{% url 'blog:detail' post.id %}" class="btn btn-primary">Read More →</a>
		            </div>
		            <div class="card-footer text-muted">
		                Posted on {{ post.pub_date }}
		            </div>
		        </div>
		        {% endfor %}
		</div>

</div>


{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogsmond{% endblock title %}

{% block content %}

	<section class="text-center">
		<div class="jumbotron container" id="imgcover">
				<br />

		    <h1 class="jumbotron-heading">Welcome to BLOGSMOND</h1>
		    	<br />
		    	<br />
		    	 <a href="{% url 'blog:all_tv' %}" class="btn btn-warning">Blogsmond Tv <span class="badge"></span></a>
		    	  <a href="{% url 'blog:all_series' %}" class="btn btn-primary">Series<span class="badge"></span></a>
		    <a href="{% url 'blog:all_post' %}" class="btn btn-success">Trends <span class="badge"></span></a>
		     <a href="{% url 'blog:all_post' %}" class="btn btn-primary">Gossip <span class="badge"></span></a>
		</div>
	</section>
	
<!-- all posts -->
<div class="container jumbotron" style="background-color: whites;">

	<div class="row">
	
		 <!-- Search Widget -->
            <div class="card col-md-12">
                <h5 class="card-header">Search</h5>
                <div class="card-body">
                    <form action="{% url 'blog:index' %}" , method="GET">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" name="query" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-secondary" type="submit">Go!</button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
            
	</div>

    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h3 class="my-4">Breaking News</h3>
            <hr>

            <!-- Blog Post  this ois just some really cool func files from web net core!-->
            <div class="card mb-5">
                <a href="{% url 'blog:breaking_detail' breaking.id %}"><img class="card-img-top" src="{{ breaking.image.url }}" alt="Card image cap" width="750px" height="450px"></a>
                <div class="card-body">
                    <a href="{% url 'blog:breaking_detail' breaking.id %}"><h3 class="card-title" style="color:teal;">{{ breaking.title }}</h3></a>
                    <p class="card-text">{{ post.body|truncatewords:15 }}</p>
                    <a href="{% url 'blog:breaking_detail' breaking.id %}" class="btn btn-primary">Read More →</a>
                </div>
                <div class="card-footer text-muted">
                    Posted on {{ breaking.pub_date }}
                </div>
            </div>

            
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

			
            <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">Blogsmond TV</h5>
                <div class="card-body">
                	<ul>
                		{% for each_tv in tv %}
		            		<li>
		            			<a href="{% url 'blog:tv_detail' each_tv.id %}" />
		            				{{ each_tv.title }}
		            			</a>
		            		</li>
                		{% endfor %}
                	</ul>
                </div>
                <a href="{% url 'blog:all_tv' %}" class="btn btn-warning">view all →</a>
            </div>
            
             <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">Blogsmond Series</h5>
                <div class="card-body">
                	<ul>
                		{% for each_series in series %}
		            		<li>
		            			<a href="{% url 'blog:series_detail' each_series.id %}" />
		            				{{ each_series.title }}
		            			</a>
		            		</li>
                		{% endfor %}
                	</ul>
                </div>
                <a href="{% url 'blog:all_series' %}" class="btn btn-primary">view all →</a>
            </div>
            
             <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">Blogsmond Stories</h5>
                <div class="card-body">
                	<ul>
                		{% for each_post in posts %}
		            		<li>
		            			<a href="{% url 'blog:post_detail' each_post.id %}" />
		            				{{ each_post.title }}
		            			</a>
		            		</li>
                		{% endfor %}
                	</ul>
                </div>
				<a href="{% url 'blog:all_post' %}" class="btn btn-success">view all →</a>
            </div>

        </div>

    </div>
    <!-- /.row -->
    
    <div class="row">
    
    	<!-- Side Widget -->
    	
    		{% for post in all_posts %}
    		<div class="col-sm-3">
		        <div class="card my-3">
		            <div class="card-body">
		            	<a href="{% url 'blog:post_detail' post.id %}">
		            		<img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap" width="50px" height="100px">
		            	
		            </div>
		            <div class="card-footer text-muted">
		            	<a href="{% url 'blog:post_detail' post.id %}">
		            		{{ post.title }}
		            	</a>
		            </div>
		        </div>
		     </div>
            {% endfor %}	
        
        
      </div>
    	

    
</div>
{% endblock content %}

blog/templates/blog/post_blog.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blog-Details{% endblock title %}

{% block content %}

	<div class="container">
			<br />
				<br />
					<br />
		<div class="jumbotron">
			<div class="row">
				<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				
                 	<div class="form-group">
                		<input  class="form-control" type="text" required="required"  name="title" placeholder="Title">
                    </div>
                    	<br />
                    <div class="form-double">
                    	<input type="file" name="photo" required="required" accept="image/*">
                   	</div>
                   		<br />
                   	<div class="form-double">
                    	<textarea name="body" rows="5" required="required" placeholder="Enter the story"></textarea>
                   	</div>
                   	<br />
                   	
                   <div class="form-double">
                    	 <button class="bttn bttn-primary">Submit!</button>
                   	</div>
                   	
                
                </form>
			</div>
		</div>
	
	</div>


{% endblock %}

blog/templates/blog/post_breaking.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogmond Breakingpost{% endblock title %}

{% block content %}

	<div class="container">
			<br />
				<br />
					<br />
					<h3>Blogmond Breakingpost</h3>
		<div class="jumbotron">
			<div class="row">
				<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				
                 	<div class="form-group">
                		<input  class="form-control" type="text" required="required"  name="title" placeholder="Title">
                    </div>
                    	<br />
                    <div class="form-double">
                    	<input type="file" name="photo" required="required" accept="image/*">
                   	</div>
                   		<br />
                   	<div class="form-double">
                    	<textarea name="body" rows="5" required="required" placeholder="Enter the story"></textarea>
                   	</div>
                   	<br />
                   	
                   <div class="form-double">
                    	 <button class="bttn bttn-primary">Submit!</button>
                   	</div>
                   	
                
                </form>
			</div>
		</div>
	
	</div>


{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogsmond Post-Details{% endblock title %}

{% block content %}
<!-- all posts -->
<div class="container">

    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-12">

            <h3 class="my-4" style="color:teal;">{{ post.title }}</h3>
            <hr>
            <p> Posted on {{ post.pub_date }}</p>
            <hr>

            <!-- Blog Post -->
            <div class="card mb-4">
                <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap" width="750px" height="450px">
                <div class="card-body">
                    <p class="card-text">{{ post.body }}</p>
                </div>
            </div>

        </div>
    </div>

</div>
<!-- /.row -->	

</div>


{% endblock content %}


<div class="row pt-3 text-center container">
			<h2 class="my-4">Recents Post</h2>
		</div>
		
		<div class="row">
				
	            {% for post in posts %}
		        <div class="card col-md-3">
		            <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap" width="750px" height="300px">
		            <div class="card-body">
		                <h3 class="card-title" style="color:teal;">{{ post.title }}</h3>
		                <p class="card-text">{{ post.body|truncatewords:15 }}</p>
		                <a href="{% url 'blog:detail' post.id %}" class="btn btn-primary">Read More →</a>
		            </div>
		            <div class="card-footer text-muted">
		                Posted on {{ post.pub_date }}
		            </div>
		        </div>
		        {% endfor %}
		</div>

blog/templates/blog/post_series.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogmond Seriespost{% endblock title %}

{% block content %}

	<div class="container">
			<br />
				<br />
					<br />
					<h3>Blogmond Seriespost</h3>
		<div class="jumbotron">
			<div class="row">
				<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				
                 	<div class="form-group">
                		<input  class="form-control" type="text" required="required"  name="title" placeholder="Title">
                    </div>
                    	<br />
                    <div class="form-double">
                    	<input type="file" name="photo" required="required" accept="image/*">
                   	</div>
                   		<br />
                   	<div class="form-double">
                    	<textarea name="body" rows="5" required="required" placeholder="Enter the story"></textarea>
                   	</div>
                   	<br />
                   	
                   <div class="form-double">
                    	 <button class="bttn bttn-primary">Submit!</button>
                   	</div>
                   	
                
                </form>
			</div>
		</div>
	
	</div>


{% endblock %}

blog/templates/blog/post_tv.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogmond TVpost{% endblock title %}

{% block content %}

	<div class="container">
			<br />
				<br />
					<br />
					<h3>Blogmond TVpos</h3>
		<div class="jumbotron">
			<div class="row">
				<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				
                 	<div class="form-group">
                		<input  class="form-control" type="text" required="required"  name="title" placeholder="Title">
                    </div>
                    	<br />
                    <div class="form-double">
                    	<input type="file" name="photo" required="required" accept="video/*">
                   	</div>
                   		<br />
                   	<div class="form-double">
                    	<textarea name="body" rows="5" required="required" placeholder="Enter the story"></textarea>
                   	</div>
                   	<br />
                   	
                   <div class="form-double">
                    	 <button class="bttn bttn-primary">Submit!</button>
                   	</div>
                   	
                
                </form>
			</div>
		</div>
	
	</div>


{% endblock %}

blog/templates/blog/series_detail.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogsmond Series-Details{% endblock title %}

{% block content %}

	<div class="container">

		<div class="row">
		    <!-- Blog Entries Column -->
		    <div class="col-md-12">

		        <h3 class="my-4" style="color:teal;">{{ series.title }}</h3>
		        <hr>
		        <p> Posted on {{ series.pub_date }}</p>
		        <hr>

		        <!-- Blog Post -->
		        <div class="card mb-4">
		            <img class="card-img-top" src="{{ series.image.url }}" alt="Card image cap" width="750px" height="450px">
		            <div class="card-body">
		                <p class="card-text">{{ series.body }}</p>
		            </div>
		        </div>

		    </div>
		</div>

	</div>


{% endblock content %}

blog/templates/blog/tv_detail.html
{% extends 'blog/base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blogsmond Tv-Details{% endblock title %}

{% block content %}

	<div class="container">

		<div class="row">
		    <!-- Blog Entries Column -->
		    <div class="col-md-12">

		        <h3 class="my-4" style="color:teal;">{{ tv.title }}</h3>
		        <hr>
		        <p> Posted on {{ tv.pub_date }}</p>
		        <hr>

		        <!-- Blog Post -->
		        <div class="card mb-4">
		           
		            <video width="100%" controls>
		            	<source src="{{ tv.video.url }}" type="video/mp4">
		            	sorry your device does not support this video
		            </video>
		            
		            <div class="card-body">
		                <p class="card-text">{{ tv.body }}</p>
		            </div>
		        </div>

		    </div>
		</div>

	</div>



{% endblock content %}